In [2]:
import glob
import os
import pandas as pd
import numpy as np

In [3]:
def getNaNs(dummy, n):
    
    name = []
    frames = []
    points = []

    for index, row in dummy.iterrows():
        for column in row.isnull().index:
            if row.isnull()[column]:
    #             print('found the NaN on %s column and %s index' %(column, index))
                name.append(n)
                frames.append(index)
                points.append(column)
                
    null_df = pd.DataFrame({'name': name,
                       'frameNumber': frames,
                       'Points': points})
    return(null_df)

In [4]:
files = glob.glob('../dataFolder/Digitization_Final_Data/*/*/*/*xyzpts.csv', recursive=True)

In [5]:
# files

In [6]:
Nan_loc = pd.DataFrame(data = None, columns = ['name', 'frameNumber', 'Points'])

for f in files:
    df = pd.read_csv(f)
    name = os.path.basename(f)
    f_null = getNaNs(df, name)
    Nan_loc = Nan_loc.append(f_null)

In [7]:
Nan_loc

                                            name frameNumber Points
0     fly3_epi_intactwings_1_complete_xyzpts.csv           0  pt1_X
1     fly3_epi_intactwings_1_complete_xyzpts.csv           0  pt1_Y
2     fly3_epi_intactwings_1_complete_xyzpts.csv           0  pt1_Z
3     fly3_epi_intactwings_1_complete_xyzpts.csv           0  pt2_X
4     fly3_epi_intactwings_1_complete_xyzpts.csv           0  pt2_Y
...                                          ...         ...    ...
8455  fly9_sc_intactwings_1_corrected_xyzpts.csv        1073  pt4_Y
8456  fly9_sc_intactwings_1_corrected_xyzpts.csv        1073  pt4_Z
8457  fly9_sc_intactwings_1_corrected_xyzpts.csv        1073  pt5_X
8458  fly9_sc_intactwings_1_corrected_xyzpts.csv        1073  pt5_Y
8459  fly9_sc_intactwings_1_corrected_xyzpts.csv        1073  pt5_Z

[280668 rows x 3 columns]

In [8]:
Nan_loc.to_csv('../dataFolder/Digitization_Final_Data/LocationsOfNans.csv')

In [9]:
# pick out non contiounous frames!

n = []
f_first = []
f_end = []
for name, subdf in Nan_loc.groupby('name'):
    # find the begining of NaN chunck
    f0=0
    for frame, row in subdf.groupby('frameNumber'):
        f1 = frame
        if f1-f0 != 1:
            n.append(name)
            f_first.append(f1)
        f0=frame
    # find the end of the NaN chunck
    f0=0
    for frame, row in subdf[::-1].groupby('frameNumber', sort = False):
        f1 = frame
        if f1-f0 != -1:
            f_end.append(f1)
        f0=frame

In [10]:
len(f_first), len(f_end), len(n)

(46, 46, 46)

In [11]:
list_to_lookAt = pd.DataFrame({'name':n,
                              'start': f_first,
                              'end': f_end})
list_to_lookAt

                                                 name  start   end
0   fly1_halLoad_loadedhaltere3_1_complete_xyzpts.csv    500   895
1                 fly1_sc_cutwing1_1_with5_xyzpts.csv    520   667
2             fly1_sc_cutwing2_1_corrected_xyzpts.csv    310   397
3             fly1_sc_cutwing3_1_corrected_xyzpts.csv    665   909
4          fly1_sc_intactwings_1_corrected_xyzpts.csv    698   775
5   fly2_halLoad_intacthalteres_1_complete_xyzpts.csv    500   627
6   fly2_halLoad_loadedhaltere1_1_complete_xyzpts.csv    500   893
7   fly2_halLoad_loadedhaltere3_1_corrected_xyzpts...    500  1180
8      fly2_halLoad_removedload_1_complete_xyzpts.csv    500   627
9             fly2_sc_cutwing1_1_corrected_xyzpts.csv    440   705
10            fly2_sc_cutwing2_2_corrected_xyzpts.csv    580  1118
11            fly2_sc_cutwing3_1_corrected_xyzpts.csv    560   691
12            fly2_sc_cutwing4_1_corrected_xyzpts.csv    560   691
13         fly2_sc_intactwings_1_corrected_xyzpts.csv      0   789
14         fly2_sc_intactwings_1_corrected_xyzpts.csv    451    28
15         fly3_epi_intactwings_1_complete_xyzpts.csv      0    98
16  fly3_halLoad_intacthalteres_1_complete_xyzpts.csv    500   594
17  fly3_halLoad_loadedhaltere2_1_complete_xyzpts.csv    500  1194
18  fly3_halLoad_loadedhaltere3_1_corrected_xyzpts...    500  1104
19  fly4_halLoad_loadedhaltere2_1_complete_xyzpts.csv    500   770
20  fly4_halLoad_loadedhaltere3_1_complete_xyzpts.csv      0   896
21  fly4_halLoad_loadedhaltere3_1_complete_xyzpts.csv    550    48
22           fly5_epi_cutwing2_1_corrected_xyzpts.csv      0    98
23  fly5_halLoad_loadedhaltere2_1_complete_xyzpts.csv    500   851
24  fly5_halLoad_loadedhaltere3_1_corrected_xyzpts...    500  1544
25            fly7_epi_cutwing4_1_complete_xyzpts.csv    374   505
26            fly7_sc_cutwing1_2_corrected_xyzpts.csv    504   536
27                 fly7_sc_cutwing2_1_with5xyzpts.csv    505   505
28            fly7_sc_cutwing3_1_corrected_xyzpts.csv    520   673
29         fly7_sc_intactwings_2_corrected_xyzpts.csv    630   892
30           fly8_epi_cutwing1_1_corrected_xyzpts.csv    500   535
31           fly8_epi_cutwing3_1_corrected_xyzpts.csv      0   761
32           fly8_epi_cutwing3_1_corrected_xyzpts.csv    549    48
33         fly8_epi_intactwings_1_complete_xyzpts.csv    500   581
34  fly8_halLoad_loadedhaltere1_1_complete_xyzpts.csv    500   703
35  fly8_halLoad_loadedhaltere3_1_corrected_xyzpts...    499  1117
36            fly8_sc_cutwing1_2_corrected_xyzpts.csv    410  1054
37            fly8_sc_cutwing2_2_corrected_xyzpts.csv    740  1219
38            fly8_sc_cutwing3_1_corrected_xyzpts.csv    615  1327
39            fly8_sc_cutwing4_1_corrected_xyzpts.csv    480   989
40         fly8_sc_intactwings_1_corrected_xyzpts.csv    620   711
41            fly9_sc_cutwing1_2_corrected_xyzpts.csv    608   964
42            fly9_sc_cutwing2_2_corrected_xyzpts.csv    616  1101
43            fly9_sc_cutwing3_1_corrected_xyzpts.csv    570   747
44            fly9_sc_cutwing4_1_corrected_xyzpts.csv    570   794
45         fly9_sc_intactwings_1_corrected_xyzpts.csv    510  1073

In [12]:
Nan_loc.loc[(Nan_loc.name == 'fly2_intacthalteres_1_complete_xyzpts.csv') &
           (Nan_loc.frameNumber < 195), :]

Empty DataFrame
Columns: [name, frameNumber, Points]
Index: []

In [13]:
Nan_loc.name.unique()

array(['fly3_epi_intactwings_1_complete_xyzpts.csv',
       'fly5_epi_cutwing2_1_corrected_xyzpts.csv',
       'fly7_epi_cutwing4_1_complete_xyzpts.csv',
       'fly8_epi_cutwing1_1_corrected_xyzpts.csv',
       'fly8_epi_cutwing3_1_corrected_xyzpts.csv',
       'fly8_epi_intactwings_1_complete_xyzpts.csv',
       'fly1_halLoad_loadedhaltere3_1_complete_xyzpts.csv',
       'fly2_halLoad_intacthalteres_1_complete_xyzpts.csv',
       'fly2_halLoad_loadedhaltere1_1_complete_xyzpts.csv',
       'fly2_halLoad_loadedhaltere3_1_corrected_xyzpts.csv',
       'fly2_halLoad_removedload_1_complete_xyzpts.csv',
       'fly3_halLoad_intacthalteres_1_complete_xyzpts.csv',
       'fly3_halLoad_loadedhaltere2_1_complete_xyzpts.csv',
       'fly3_halLoad_loadedhaltere3_1_corrected_xyzpts.csv',
       'fly4_halLoad_loadedhaltere2_1_complete_xyzpts.csv',
       'fly4_halLoad_loadedhaltere3_1_complete_xyzpts.csv',
       'fly5_halLoad_loadedhaltere2_1_complete_xyzpts.csv',
       'fly5_halLoad_loadedhaltere3_1_corrected_xyzpts.csv',
       'fly8_halLoad_loadedhaltere1_1_complete_xyzpts.csv',
       'fly8_halLoad_loadedhaltere3_1_corrected_xyzpts.csv',
       'fly1_sc_cutwing1_1_with5_xyzpts.csv',
       'fly1_sc_cutwing2_1_corrected_xyzpts.csv',
       'fly1_sc_cutwing3_1_corrected_xyzpts.csv',
       'fly1_sc_intactwings_1_corrected_xyzpts.csv',
       'fly2_sc_cutwing1_1_corrected_xyzpts.csv',
       'fly2_sc_cutwing2_2_corrected_xyzpts.csv',
       'fly2_sc_cutwing3_1_corrected_xyzpts.csv',
       'fly2_sc_cutwing4_1_corrected_xyzpts.csv',
       'fly2_sc_intactwings_1_corrected_xyzpts.csv',
       'fly7_sc_cutwing1_2_corrected_xyzpts.csv',
       'fly7_sc_cutwing2_1_with5xyzpts.csv',
       'fly7_sc_cutwing3_1_corrected_xyzpts.csv',
       'fly7_sc_intactwings_2_corrected_xyzpts.csv',
       'fly8_sc_cutwing1_2_corrected_xyzpts.csv',
       'fly8_sc_cutwing2_2_corrected_xyzpts.csv',
       'fly8_sc_cutwing3_1_corrected_xyzpts.csv',
       'fly8_sc_cutwing4_1_corrected_xyzpts.csv',
       'fly8_sc_intactwings_1_corrected_xyzpts.csv',
       'fly9_sc_cutwing1_2_corrected_xyzpts.csv',
       'fly9_sc_cutwing2_2_corrected_xyzpts.csv',
       'fly9_sc_cutwing3_1_corrected_xyzpts.csv',
       'fly9_sc_cutwing4_1_corrected_xyzpts.csv',
       'fly9_sc_intactwings_1_corrected_xyzpts.csv'], dtype=object)